# https://docs.github.com/en/free-pro-team@latest/actions/creating-actions/metadata-syntax-for-github-actions
name: GitHub Actions Template

description: Template for GitHub actions.

author: technote-space

inputs:
  GITHUB_TOKEN:
    description: Secret GitHub API token to use for making API requests.
    default: ${{ github.token }}
    required: false

#outputs:
#  result:
#    description: action result

branding:
  # https://feathericons.com/
  # e.g. https://haya14busa.github.io/github-action-brandings/
  icon: 'package'
  color: 'orange'

runs:
  using: node16
  main: lib/main.js
#  pre: lib/pre.js
#  pre-if: 'runner.os == linux'
#  post: lib/post.js
#  post-if: 'success()'
